baseURL = "https://www.tiri.uk"
title = "Tiri.Uk"
theme = "tiri-elegant"
publishDir = "docs"

defaultContentLanguage = "pl"

disableKinds = ["taxonomy", "term"]

[params]
  mainSections = ["posts"]

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "https://ctrlexist2000-source.github.io/tiri.uk/"
  weight = 1
[[menu.main]]
  name = "Archiwum"
  url = "/archiwum/"
  weight = 25

[[menu.main]]
  name = "About"
  url = "https://ctrlexist.my.canva.site/about-me"
  weight = 30

[[menu.main]]
  name = "Contact"
  url = "https://ctrlexist.my.canva.site/connect"
  weight = 40
