baseURL = "https://www.tiri.uk/"

title = "Tiri.Uk"
theme = "tiri-elegant"
paginate = 10
defaultContentLanguage = "en"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
summaryLength = 40

[params]
  author = "Tiri"
  description = "Personal blog by Tiri"
  ShowReadingTime = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "Archiwum"
    name = "Archiwum"
    url = "/archiwum/"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30
